# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-default:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-1.9.0-cuda11.1-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-addone:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-1.10.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-addtwo:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-1.11.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-addthree:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-1.12.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-addfour:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-1.13.0-cuda11.6-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-addfive:
    runs-on: ubuntu-latest
    container: woqidaideshi/bagua:master-pytorch-2.0.0-cuda11.7-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
