name: bagua-net ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test env
      run: |
        uname -a
        cat /etc/os-release
        python --version || echo no python
        python3 --version || echo no python3
        make --version || echo no make
        cmake --version || echo no cmake
        rustc --version || echo no rust
        gcc --version || echo no gcc
        nvcc --version || echo no cuda
        lspci | grep NVIDI || echo no GPU
        nvidia-smi || echo no nvidia-smi
        pip3 list | grep torch || echo no torch in pip3
        pip3 list | grep numpy || echo no numpy in pip3
        pip3 list | grep tqdm || echo no tqdm in pip3
        pip3 list | grep bagua || echo no bagua in pip3
        pip3 list | grep cmake || echo no cmake in pip3
        pip list | grep torch || echo no torch in pip
        pip list | grep numpy || echo no numpy in pip
        pip list | grep tqdm || echo no tqdm in pip
        pip list | grep bagua || echo no bagua in pip
        pip list | grep cmake || echo no cmake in pip
    - name: Unit Test
      run: cd rust/bagua-net/cc && make test
