# This is a basic workflow to help you get started with Actions

name: pytype

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.9.0-cuda11.1-cudnn8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: test env
        run: |
          uname -a
          cat /etc/os-release
          python --version || echo no python
          python3 --version || echo no python3
          make --version || echo no make
          cmake --version || echo no cmake
          rustc --version || echo no rust
          gcc --version || echo no gcc
          nvcc --version || echo no cuda
          lspci | grep NVIDI || echo no GPU
          nvidia-smi || echo no nvidia-smi
          pip3 list | grep torch || echo no torch in pip3
          pip3 list | grep numpy || echo no numpy in pip3
          pip3 list | grep tqdm || echo no tqdm in pip3
          pip3 list | grep bagua || echo no bagua in pip3
          pip list | grep torch || echo no torch in pip
          pip list | grep numpy || echo no numpy in pip
          pip list | grep tqdm || echo no tqdm in pip
          pip list | grep bagua || echo no bagua in pip
      - name: Pytype Python Checker
        # You may pin to the exact commit or the version.
        # uses: theahura/pytype-action@38cf548b60f6da64118a1d74e3277efcf533e1a2
        uses: NOBLES5E/pytype-action@main
        with:
          args: -d import-error bagua
